% Nathan Holmes
% 11/17/2017
% Section 208
% Homework 9

function [ ] = radio_colors_GUI()
% Radio buttons are used to change the color of the figure background.



% 'S' is a STRUCTURE ARRAY which contains the data that the GUI uses to
% pass handles and other information between the main function and the
% callbacks.

% Figure properties
S.fh = figure('units','pixels',...
    'position',[300 300 250 200],...
    'menubar','none',...
    'name','COLORS!',...
    'numbertitle','off',...
    'resize','off');
% Button group
S.bg = uibuttongroup('units','pix',...
    'pos',[20 100 210 90]);
% Radio Button 1
S.rd(1) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[20 50 70 30],...
    'string','Red');
% Radio Button 2
S.rd(2) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[20 10 70 30],...
    'string','Yellow');
% Radio Button 3
S.rd(3) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[120 50 70 30],...
    'string','Green');
% Radio Button 4
S.rd(4) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[120 10 70 30],...
    'string','Blue');
% Edit Box -- deleted
% Button with callback 'pb_call' and the added input, 'S', a structure
% array with handles and other GUI information.
S.pb = uicontrol('style','push',...
    'unit','pix',...
    'position',[75 20 100 30],...
    'string','Pick Color',...
    'callback',{@pb_call,S});


end

function [] = pb_call(source,eventData,S)
% Callback for pushbutton.

% Instead of switch, we could use num2str on:
% get(S.bg,'selectedobject')==S.rd      (or similar) to determine which
% radio button was selected when the button was pressed

buttonSelected = S.bg.SelectedObject;

switch buttonSelected
    % Sets the editbox string based on the button that was selected. Could
    % be changed to do lots of things.
    case S.rd(1) % if red
        set(S.fh,'color','r');
    case S.rd(2) % if yellow
        set(S.fh,'color','y');
    case S.rd(3) % if green
        set(S.fh,'color','g');
    case S.rd(4) % if blue
        set(S.fh,'color','b');
    otherwise
        set(S.fh,'color','m') % Not very likely
end

end